### ISSUE TITLE
ProgramFiles normalisation fails on 32-bit Windows

### ISSUE THREAD

**Issue by lvillani** [lvillani/just-install#63]
```
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x6604c0, 0x7fc2ef)
        c:/go/src/pkg/runtime/panic.c:279 +0xe9
main.normalizeProgramFiles()
        C:/Users/Lorenzo/Documents/GitHub/just-install/just-install.go:70 +0xe2
main.main()
        C:/Users/Lorenzo/Documents/GitHub/just-install/just-install.go:55 +0x21

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        c:/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        c:/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445
```

**Comment by lvillani** [comment]
Should be fixed in 2.3.1. Closing.
